add  time_zone configutation to users
openpoke/decidim pull request #11
Opened 2022-08-23 16:05 UTC by antopalidi

2022-08-23 20:11 UTC, antopalidi commented
<img width="800" alt="screen" src="https://user-images.githubusercontent.com/60363870/186256152-f432ef44-eb17-49c0-b344-0b91eefc7655.png">

2022-08-25 11:55 UTC, microstudi requested changes
Hi @antopalidi 
this is an initial review, but you can already apply (some) of the changes. I'll fully test it later and give you more feedbacks and hints on how to proceed with tests

2022-08-25 11:55 UTC, microstudi commented on decidim-core/app/controllers/concerns/decidim/use_organization_time_zone.rb
> +        @organization_time_zone ||= current_organization.time_zone ||= current_user.time_zone
```suggestion
        @organization_time_zone ||= current_user.time_zone || current_organization.time_zone
```
we want the assignation of this to check the user first, then the organization.
Also: carefull to do double assignations with the `||=` statement.

2022-08-25 11:55 UTC, microstudi commented on decidim-core/db/migrate/20220823094517_add_time_zone_to_users.rb
> +    add_column :decidim_users, :time_zone, :string, limit: 255, default: "UTC"
```suggestion
    add_column :decidim_users, :time_zone, :string
```
Let's not add a default here, we will use the organization timezone if this is empty

2022-08-26 07:09 UTC, microstudi requested changes
Hi @antopalidi 
It seems that default values on the `account_form.rb` cannot extract data from the context, instead we can add the default value in the view (as suggested in the comments).
Also, it is not necessary to enforce the presence of a timezone to the user, we will just use the organization if not present.

We also need to add a test case in the file `decidim-core/spec/controllers/concerns/use_organization_time_zone_spec.rb` and add a case for when the time zone is defined by the user and see that it takes precedence over the organizaion (only if present)

2022-08-26 07:09 UTC, microstudi commented on decidim-core/app/models/decidim/user.rb
> +    validates :time_zone, presence: true, time_zone: true
```suggestion
    validates :time_zone, time_zone: true, if:-> { timezone.present? }
```
We don't need to enforce timezones here

2022-08-26 07:09 UTC, microstudi commented on decidim-core/app/views/decidim/account/show.html.erb
> +      <%= f.time_zone_select :time_zone %>
```suggestion
      <%= f.time_zone_select :time_zone, nil, default: current_organization.time_zone %>
      <p class="help-text"><%= t(".time_zone_helper") %></p>
```
As it doesn't seem possible to put the default in the form we can add it here
It would be also nice to add a helper text with this phrase (needs to be added in `decidim-core/config/en.yml`):
*Use your personal time zone to display dates in your local time when you are logged in*

2022-08-26 07:09 UTC, microstudi commented on decidim-core/spec/commands/decidim/update_account_spec.rb
> +        time_zone: "UTC"
```suggestion
        time_zone: timezone
```
As timezone is not strictly mandatory, we can define a `let` variable instead an test that it updates if defined and does nothing if not.
```ruby
let(:timezone) { "UTC" }
```

2022-08-26 07:09 UTC, microstudi commented on decidim-core/spec/commands/decidim/update_account_spec.rb
> +
```suggestion
      it "updates the time zone" do
        expect { command.call }.to broadcast(:ok)
        expect(user.reload.time_zone).to eq("UTC")
      end

      context "when timezone is not defined" do
        let(:timezone) { "" }
        it "returns ok" do
           expect { command.call }.to broadcast(:ok)
           expect(user.reload.time_zone).to eq("")
        end
      end

      context "when timezone is invalid" do
        let(:timezone) { "giberish" }
        it "returns invalid" do
           expect { command.call }.to broadcast(:invalid)
        end
      end
```

We can add more test cases here, maybe the last one could be better tested in the `account_form_spec.rb`, as you preferer.

2022-08-26 07:09 UTC, microstudi commented on decidim-core/spec/forms/account_form_spec.rb
> +          expect(subject).not_to be_valid
```suggestion
          expect(subject).to be_valid
```
Should be valid in this case.

We should add a case when timezone is invalid (not a valid time zone, like in the suggestion for the `update_account_spec.rb`

2022-08-26 14:50 UTC, microstudi requested changes
Almost there!
If left a comment, please check it out.

On the other hand, we need to look at the failing tests, the first one is about linting the YAML locale file, this can be done automatically by executing:

`bundle exec i18n-tasks normalize --locales en`

The second one is because (I think) you need to add 
```ruby
let(:timezone) { "UTC" }
```
at the same level of the `let(:data)` in the file `update_account_spec.rb`

2022-08-26 14:50 UTC, microstudi commented on decidim-core/app/controllers/concerns/decidim/use_organization_time_zone.rb
> +        @organization_time_zone ||= current_organization.time_zone || current_user.time_zone
```suggestion
        @organization_time_zone ||= current_user.time_zone || current_organization.time_zone
```
We should first check the user's timezone and, if empty, the organization's

2022-08-26 14:50 UTC, microstudi commented on decidim-core/app/forms/decidim/account_form.rb
> +    validates :time_zone, time_zone: true
```suggestion
    validates :time_zone, time_zone: true, if: -> { time_zone.present? }
```
We should validate this only if specified

2022-08-30 10:49 UTC, microstudi approved these changes
This is fantastic @antopalidi !
I've added an additional test, but that's it!
ready to deploy!

2025-03-05 13:25 UTC, closed without merging